name: build pipeline
on:
  push:
    branches:
    - master
  # Manually trigger from Actions tab
  workflow_dispatch:
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: all
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: actions/docker_action@v2
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
